INSERT INTO "CUSTOMERS" ("ID","NAME","EMAIL") VALUES
('1', 'Ashutosh Sahoo','ashu@example.com');

INSERT INTO "ROLES" VALUES
(1000, 'ROLE_ORDER_VIEWER'),
(1001, 'ROLE_ORDER_ADMINISTRATOR'),
(1002, 'ROLE_APP_ADMINISTRATOR');
